### PR TITLE
Renaming exception handling method and moving hardcoded paths to command-line arguments

### PR DESCRIPTION
**Pull request by tzhechev**
Странно, изяде ми description-а. Та тук има малко рефакторинг, промяна на името на метода за exception handling и извеждане на hard coded path strings към command line arguments.

### CODE REVIEW

**Review by miaaaooow — APPROVED** [review]
It was part of the sports spirit at a competition ;)

**Review by miaaaooow — COMMENTED** [review]
I would prefer to have a configuration file and config defaults (maybe some relative paths). Can you add this as well? Were you able to start Gate this way? (It is known to treat paths with some... "hesitation" :))

**Comment by tzhechev** [comment]
Yup, started it and did a test run like this. I can add a config file too, it won't be an issue. Preferred this initially since it keeps the repo agnostic to local platforms and paths. I can have it read from a file in the base folder if no command line args are provided and the file is there, does that seem OK?

**Comment by miaaaooow** [comment]
Yep, sounds great :)

**Comment by tzhechev** [comment]
Oh, hey, it got added to the pull request right away. Does this seem OK then? You'll need to create your own config.properties of course. Mine looks like this:

resourcespath=C:\\Users\\User\\git\\OpenLexMine\\sloth.works.hakathon\\gate-experiment\\src\\main\\resources\\
gatepath=C:\\Program Files\\GATE_Developer_8.4.1\\

**Comment by miaaaooow** [comment]
I think it is a nice idea to add exemplary config file. It can be with empty values, or, I would always prefer an example. It can start with <PROJECT_HOME> instead of you actual project home path.

**Comment by tzhechev** [comment]
Won't GIT keep bugging you about it if it's in there though? That's generally why I avoid putting anything user specific in the source control. Do you mean <PROJECT_HOME> as an environmental variable? I went with the root folder since it tends to be the base when you run the project and it keeps thing somewhat simpler.

**Comment by miaaaooow** [comment]
I would normally add it with just empty string values, but in case of GATE, it might be counter-intuitive for a new-comer where to point the paths to (GATE root? GATE resources root?, etc.). I'd just make it as easy as possible for a new user/contributor of the project.

**Comment by miaaaooow** [comment]
... Maybe add an example as a comment, as a compromise.

**Comment by tzhechev** [comment]
Alright. I think I can make it easier if I put placeholders down and have the resulting error guide users to putting the proper values down.

**Comment by tzhechev** [comment]
Bump? :)

**Pull request merged**
